package help

import "fmt"

func PrintUsage() {
	fmt.Println("Docu-Jarvis CLI - AI-powered documentation tool")
	fmt.Println("\nCommands:")
	fmt.Println("  -update-docs <files>      Update existing documentation")
	fmt.Println("  -write-docs <topics>      Write new documentation")
	fmt.Println("  -debug <from> <to> <bug>  Find which commit caused a bug")
	fmt.Println("  -check-staging [settings] Review staged code quality")
	fmt.Println("  -explain <commit> [question] Explain a commit interactively")
	fmt.Println("  -config                   Edit configuration (repo URL, code standards)")
	fmt.Println("  -version                  Show version and check for updates")
	fmt.Println("  -update                   Update to the latest version")
	fmt.Println("  -help [command]           Show help")
	fmt.Println("\nFirst Time Setup:")
	fmt.Println("  docu-jarvis -config       Configure repo URL and GitHub token")
	fmt.Println("\nFor detailed help on a command:")
	fmt.Println("  docu-jarvis -help update-docs")
	fmt.Println("  docu-jarvis -help write-docs")
	fmt.Println("  docu-jarvis -help debug")
	fmt.Println("  docu-jarvis -help check-staging")
	fmt.Println("  docu-jarvis -help explain")
	fmt.Println()
}

func PrintUpdateDocsHelp() {
	fmt.Println("Docu-Jarvis - Update Documentation Mode")
	fmt.Println("\nDescription:")
	fmt.Println("  Updates existing documentation by analyzing the current codebase and ensuring")
	fmt.Println("  documentation accurately reflects the actual implementation.")
	fmt.Println("\nUsage:")
	fmt.Println("  docu-jarvis -update-docs <files>")
	fmt.Println("  docu-jarvis -update-docs <files> -custom \"your custom prompt\"")
	fmt.Println("\nArguments:")
	fmt.Println("  all              Update all markdown files in documentation/")
	fmt.Println("  <file.md>        Update a specific file (e.g., 'api.md')")
	fmt.Println("  <files>          Update multiple files, comma-separated (e.g., 'api.md,db.md')")
	fmt.Println("\nOptional Flags:")
	fmt.Println("  -custom \"prompt\" Use a custom prompt instead of the default update instructions")
	fmt.Println("                   Useful for specific update requirements or formatting")
	fmt.Println("\nNote:")
	fmt.Println("  - You can omit the .md extension (e.g., 'api' works like 'api.md')")
	fmt.Println("  - Multiple files are processed concurrently for speed")
	fmt.Println("  - Only documentation files are modified, never source code")
	fmt.Println("\nExamples:")
	fmt.Println("  # Standard update")
	fmt.Println("  docu-jarvis -update-docs all")
	fmt.Println("  docu-jarvis -update-docs api")
	fmt.Println("  docu-jarvis -update-docs \"api.md,database.md,setup.md\"")
	fmt.Println()
	fmt.Println("  # Custom prompt update")
	fmt.Println("  docu-jarvis -update-docs api -custom \"Add more code examples and simplify explanations\"")
	fmt.Println("  docu-jarvis -update-docs all -custom \"Update all diagrams to use mermaid syntax\"")
	fmt.Println("\nWhat it does:")
	fmt.Println("  1. Clones your repository to /tmp")
	fmt.Println("  2. Reads the documentation file(s)")
	fmt.Println("  3. Analyzes related code in the codebase")
	fmt.Println("  4. Updates documentation to match current implementation (or per custom prompt)")
	fmt.Println("  5. Creates a pull request with changes")
	fmt.Println()
}

func PrintWriteDocsHelp() {
	fmt.Println("Docu-Jarvis - Write Documentation Mode")
	fmt.Println("\nDescription:")
	fmt.Println("  Generates new comprehensive documentation for specified topics by analyzing")
	fmt.Println("  the codebase and creating structured markdown files.")
	fmt.Println("\nUsage:")
	fmt.Println("  docu-jarvis -write-docs <topics>")
	fmt.Println("\nArguments:")
	fmt.Println("  <topic>          A single topic to document (e.g., 'API Authentication')")
	fmt.Println("  <topics>         Multiple topics, comma-separated (e.g., 'API,Database,Cache')")
	fmt.Println("\nNote:")
	fmt.Println("  - Topics can be descriptive phrases (e.g., 'Payment Processing Flow')")
	fmt.Println("  - Multiple topics are processed concurrently")
	fmt.Println("  - Checks for existing documentation and prompts before overwriting")
	fmt.Println("  - Files are created in documentation/ folder with appropriate names")
	fmt.Println("\nExamples:")
	fmt.Println("  docu-jarvis -write-docs \"API Authentication\"")
	fmt.Println("  docu-jarvis -write-docs \"Subscription Management\"")
	fmt.Println("  docu-jarvis -write-docs \"API,Database Schema,Caching Strategy\"")
	fmt.Println("\nWhat it does:")
	fmt.Println("  1. Clones your repository to /tmp")
	fmt.Println("  2. Checks if documentation already exists for the topic")
	fmt.Println("  3. If exists, prompts: update, write new, or skip")
	fmt.Println("  4. Analyzes codebase to understand the topic")
	fmt.Println("  5. Generates comprehensive documentation following best practices")
	fmt.Println("  6. Creates markdown file in documentation/ folder")
	fmt.Println("  7. Creates a pull request with new documentation")
	fmt.Println("\nDocumentation Structure:")
	fmt.Println("  Each document includes:")
	fmt.Println("  - Overview and key characteristics")
	fmt.Println("  - High-level architecture with diagrams")
	fmt.Println("  - Core components breakdown")
	fmt.Println("  - Data flow explanations")
	fmt.Println("  - Detailed code implementation with examples")
	fmt.Println("  - Integration points")
	fmt.Println("  - Configuration options")
	fmt.Println("  - Monitoring and operations")
	fmt.Println()
}

func PrintDebugHelp() {
	fmt.Println("Docu-Jarvis - Debug Mode")
	fmt.Println("\nDescription:")
	fmt.Println("  Analyzes git commits within a date range to identify which commit")
	fmt.Println("  likely introduced a specific bug using AI-powered code analysis.")
	fmt.Println("\nUsage:")
	fmt.Println("  docu-jarvis -debug <from-date> <to-date> <bug-description>")
	fmt.Println("\nArguments:")
	fmt.Println("  <from-date>        Start date (format: YYYY-MM-DD)")
	fmt.Println("  <to-date>          End date (format: YYYY-MM-DD)")
	fmt.Println("  <bug-description>  Description of the bug to investigate")
	fmt.Println("\nDate Format:")
	fmt.Println("  - Use ISO format: YYYY-MM-DD (e.g., '2024-11-01')")
	fmt.Println("  - Can also use relative dates: '2 weeks ago', 'yesterday'")
	fmt.Println("  - From date should be earlier than to date")
	fmt.Println("\nExamples:")
	fmt.Println("  docu-jarvis -debug \"2024-11-01\" \"2024-11-07\" \"null pointer in payment processing\"")
	fmt.Println("  docu-jarvis -debug \"2024-10-15\" \"2024-10-20\" \"subscription not being created\"")
	fmt.Println("  docu-jarvis -debug \"1 week ago\" \"today\" \"API returns 500 error\"")
	fmt.Println("\nWhat it does:")
	fmt.Println("  1. Clones your repository to /tmp")
	fmt.Println("  2. Retrieves all commits between the specified dates")
	fmt.Println("  3. Analyzes each commit concurrently with Claude AI")
	fmt.Println("  4. Identifies which commit likely caused the bug (with confidence score)")
	fmt.Println("  5. Explains what in the commit introduced the bug")
	fmt.Println("\nOutput:")
	fmt.Println("  Shows the commit hash, author, date, message, confidence percentage,")
	fmt.Println("  and detailed explanation of what caused the bug.")
	fmt.Println()
}

func PrintCheckStagingHelp() {
	fmt.Println("Docu-Jarvis - Check Staging Mode")
	fmt.Println("\nDescription:")
	fmt.Println("  Reviews code in git staging area against your configured code quality")
	fmt.Println("  standards using AI-powered analysis.")
	fmt.Println("\nUsage:")
	fmt.Println("  docu-jarvis -check-staging          Review staged code")
	fmt.Println("  docu-jarvis -check-staging settings Edit code standards")
	fmt.Println("\nArguments:")
	fmt.Println("  (none)       Review currently staged code")
	fmt.Println("  settings     Edit your code quality standards")
	fmt.Println("\nSetting Up Standards:")
	fmt.Println("  First time: Run 'docu-jarvis -check-staging settings' to configure")
	fmt.Println("  your code standards. These are saved to ~/.docu-jarvis-settings.txt")
	fmt.Println("\nExamples:")
	fmt.Println("  # First, configure your standards")
	fmt.Println("  docu-jarvis -check-staging settings")
	fmt.Println()
	fmt.Println("  # Then review your staged code")
	fmt.Println("  git add .")
	fmt.Println("  docu-jarvis -check-staging")
	fmt.Println()
	fmt.Println("  # Update standards later")
	fmt.Println("  docu-jarvis -check-staging settings")
	fmt.Println("\nWhat it does:")
	fmt.Println("  1. Loads your code standards from ~/.docu-jarvis-settings.txt")
	fmt.Println("  2. Gets the diff of staged changes (git diff --cached)")
	fmt.Println("  3. Reviews code against your standards with Claude AI")
	fmt.Println("  4. Shows compliance status and recommendations")
	fmt.Println("\nOutput:")
	fmt.Println("  - Detailed reasoning about code quality")
	fmt.Println("  - Compliance status (COMPLIANT/NON_COMPLIANT/PARTIALLY_COMPLIANT)")
	fmt.Println("  - Specific recommendations for improvements")
	fmt.Println()
}

func PrintExplainHelp() {
	fmt.Println("Docu-Jarvis - Explain Commit Mode")
	fmt.Println("\nDescription:")
	fmt.Println("  Provides an interactive AI-powered explanation of a specific commit.")
	fmt.Println("  Have a conversation with Claude to understand what changed and why.")
	fmt.Println("\nUsage:")
	fmt.Println("  docu-jarvis -explain <commit-hash>")
	fmt.Println("  docu-jarvis -explain <commit-hash> \"initial question\"")
	fmt.Println("\nArguments:")
	fmt.Println("  <commit-hash>       The commit hash (full or short)")
	fmt.Println("  \"initial question\"  Optional first question to ask")
	fmt.Println("\nExamples:")
	fmt.Println("  # Get general explanation of a commit")
	fmt.Println("  docu-jarvis -explain abc123")
	fmt.Println()
	fmt.Println("  # Start with a specific question")
	fmt.Println("  docu-jarvis -explain abc123 \"What files were changed?\"")
	fmt.Println("  docu-jarvis -explain abc123 \"Why was this refactoring needed?\"")
	fmt.Println("\nWhat it does:")
	fmt.Println("  1. Clones your repository to /tmp")
	fmt.Println("  2. Fetches the commit details and diff")
	fmt.Println("  3. Starts an interactive conversation with Claude AI")
	fmt.Println("  4. Maintains conversation context for follow-up questions")
	fmt.Println("  5. Claude can search the codebase for additional context")
	fmt.Println("\nInteractive Mode:")
	fmt.Println("  Once in conversation mode:")
	fmt.Println("  - Ask any questions about the commit")
	fmt.Println("  - Request clarification on specific changes")
	fmt.Println("  - Explore why certain decisions were made")
	fmt.Println("  - Type 'exit' or 'quit' to end the conversation")
	fmt.Println("\nExample Conversation:")
	fmt.Println("  You: What was the main change in this commit?")
	fmt.Println("  Claude: This commit refactored the authentication system...")
	fmt.Println("  You: Why was the old approach problematic?")
	fmt.Println("  Claude: The previous implementation had a security vulnerability...")
	fmt.Println("  You: exit")
	fmt.Println()
}

